import { Partner } from "@/utils/types";

export const partners: Partner[] = [
  {
    id: 0,
    name: "John Doe",
    email: "john.doe@example.com",
    number: "+64210000001",
    nextStepDate: new Date("2023-08-15"),
    pledgedAmount: 500,
    confirmedDate: new Date("2023-08-25"),
    confirmedAmount: 500,
    notes: "Met at the conference last month.",
    status: "Confirmed",
    saved: true,
  },
  {
    id: 1,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    number: "+64210000002",
    nextStepDate: new Date("2023-08-16"),
    pledgedAmount: 300,
    confirmedDate: undefined,
    confirmedAmount: 0,
    notes: "Considering increasing the pledge.",
    status: "Pledged",
    saved: false,
  },
  {
    id: 2,
    name: "Alice Brown",
    email: "alice.brown@example.com",
    number: "+64210000003",
    nextStepDate: new Date("2023-08-17"),
    pledgedAmount: 0,
    confirmedDate: undefined,
    confirmedAmount: 0,
    notes: "Needs more information.",
    status: "Contacted",
    saved: true,
  },
  {
    id: 3,
    name: "Bob Johnson",
    email: "bob.johnson@example.com",
    number: "+64210000004",
    nextStepDate: new Date("2023-08-18"),
    pledgedAmount: 0,
    confirmedDate: undefined,
    confirmedAmount: 0,
    notes: "Left a voicemail.",
    status: "Letter Sent",
    saved: false,
  },
  {
    id: 4,
    name: "Emma Wilson",
    email: "emma.wilson@example.com",
    number: "+64210000005",
    nextStepDate: undefined,
    pledgedAmount: 0,
    confirmedDate: undefined,
    confirmedAmount: 0,
    notes: "No response yet.",
    status: "Asked",
    saved: true,
  },
  {
    id: 5,
    name: "Michael Lee",
    email: undefined,
    number: undefined,
    nextStepDate: undefined,
    pledgedAmount: 0,
    confirmedDate: undefined,
    confirmedAmount: 0,
    notes: "",
    status: "To Ask",
    saved: false,
  },
  {
    id: 6,
    name: "Olivia Clark",
    email: "olivia.clark@example.com",
    number: "+64210000007",
    nextStepDate: new Date("2023-08-20"),
    pledgedAmount: 1000,
    confirmedDate: new Date("2023-08-30"),
    confirmedAmount: 1000,
    notes: "Wants to discuss further opportunities.",
    status: "Confirmed",
    saved: true,
  },
  {
    id: 7,
    name: "James Walker",
    email: "james.walker@example.com",
    number: "+64210000008",
    nextStepDate: undefined,
    pledgedAmount: 0,
    confirmedDate: undefined,
    confirmedAmount: 0,
    notes: "Will follow up next week.",
    status: "Letter Sent",
    saved: false,
  },
  {
    id: 8,
    name: "Sophia Hall",
    email: "sophia.hall@example.com",
    number: "+64210000009",
    nextStepDate: new Date("2023-08-22"),
    pledgedAmount: 0,
    confirmedDate: undefined,
    confirmedAmount: 0,
    notes: "Waiting for response.",
    status: "Contacted",
    saved: true,
  },
  {
    id: 9,
    name: "Liam Adams",
    email: "liam.adams@example.com",
    number: "+64210000010",
    nextStepDate: new Date("2023-08-23"),
    pledgedAmount: 750,
    confirmedDate: undefined,
    confirmedAmount: 0,
    notes: "Tentatively agreed.",
    status: "Pledged",
    saved: false,
  },
  {
    id: 10,
    name: "Ava Baker",
    email: "ava.baker@example.com",
    number: "+64210000011",
    nextStepDate: new Date("2023-08-24"),
    pledgedAmount: 0,
    confirmedDate: undefined,
    confirmedAmount: 0,
    notes: "Interested, but unsure.",
    status: "Rejected",
    saved: true,
  },
  {
    id: 11,
    name: "William Evans",
    email: "william.evans@example.com",
    number: "+64210000012",
    nextStepDate: new Date("2023-08-25"),
    pledgedAmount: 0,
    confirmedDate: undefined,
    confirmedAmount: 0,
    notes: "Requires more details.",
    status: "Letter Sent",
    saved: false,
  },
  {
    id: 12,
    name: "Mia Carter",
    email: "mia.carter@example.com",
    number: "+64210000013",
    nextStepDate: new Date("2023-08-26"),
    pledgedAmount: 600,
    confirmedDate: new Date("2023-09-01"),
    confirmedAmount: 600,
    notes: "Happy to contribute.",
    status: "Confirmed",
    saved: true,
  },
  {
    id: 13,
    name: "Benjamin Phillips",
    email: undefined,
    number: undefined,
    nextStepDate: undefined,
    pledgedAmount: 0,
    confirmedDate: undefined,
    confirmedAmount: 0,
    notes: "",
    status: "To Ask",
    saved: false,
  },
  {
    id: 14,
    name: "Charlotte Mitchell",
    email: "charlotte.mitchell@example.com",
    number: "+64210000015",
    nextStepDate: new Date("2023-08-27"),
    pledgedAmount: 0,
    confirmedDate: undefined,
    confirmedAmount: 0,
    notes: "Asked for more time to decide.",
    status: "Contacted",
    saved: true,
  },
  {
    id: 15,
    name: "Elijah Perez",
    email: "elijah.perez@example.com",
    number: "+64210000016",
    nextStepDate: new Date("2023-08-28"),
    pledgedAmount: 800,
    confirmedDate: undefined,
    confirmedAmount: 0,
    notes: "Needs confirmation.",
    status: "Pledged",
    saved: false,
  },
  {
    id: 16,
    name: "Amelia Harris",
    email: "amelia.harris@example.com",
    number: "+64210000017",
    nextStepDate: new Date("2023-08-29"),
    pledgedAmount: 400,
    confirmedDate: new Date("2023-09-03"),
    confirmedAmount: 400,
    notes: "Looking forward to the partnership.",
    status: "Confirmed",
    saved: true,
  },
  {
    id: 17,
    name: "Lucas Edwards",
    email: undefined,
    number: undefined,
    nextStepDate: undefined,
    pledgedAmount: 0,
    confirmedDate: undefined,
    confirmedAmount: 0,
    notes: "",
    status: "To Ask",
    saved: false,
  },
  {
    id: 18,
    name: "Harper Collins",
    email: "harper.collins@example.com",
    number: "+64210000019",
    nextStepDate: new Date("2023-08-30"),
    pledgedAmount: 0,
    confirmedDate: undefined,
    confirmedAmount: 0,
    notes: "Possibly interested.",
    status: "Contacted",
    saved: true,
  },
];
