import { Partner } from "@/utils/types";

export const partners: Partner[] = [
  {
    id: 0,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    number: "+64210000001",
    sentDate: new Date("2023-08-15"),
    pledgedAmount: 500,
    confirmedDate: new Date("2023-08-25"),
    confirmedAmount: 500,
    notes: "Met at the conference last month.",
    status: "Confirmed",
  },
  {
    id: 1,
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    number: "+64210000002",
    sentDate: new Date("2023-08-16"),
    pledgedAmount: 300,
    confirmedDate: undefined,
    confirmedAmount: undefined,
    notes: "Considering increasing the pledge.",
    status: "Pledged",
  },
  {
    id: 2,
    firstName: "Alice",
    lastName: "Brown",
    email: "alice.brown@example.com",
    number: "+64210000003",
    sentDate: new Date("2023-08-17"),
    pledgedAmount: undefined,
    confirmedDate: undefined,
    confirmedAmount: undefined,
    notes: "Needs more information.",
    status: "Contacted",
  },
  {
    id: 3,
    firstName: "Bob",
    lastName: "Johnson",
    email: "bob.johnson@example.com",
    number: "+64210000004",
    sentDate: new Date("2023-08-18"),
    pledgedAmount: undefined,
    confirmedDate: undefined,
    confirmedAmount: undefined,
    notes: "Left a voicemail.",
    status: "Letter Sent",
  },
  {
    id: 4,
    firstName: "Emma",
    lastName: "Wilson",
    email: "emma.wilson@example.com",
    number: "+64210000005",
    sentDate: undefined,
    pledgedAmount: undefined,
    confirmedDate: undefined,
    confirmedAmount: undefined,
    notes: "No response yet.",
    status: "Asked",
  },
  {
    id: 5,
    firstName: "Michael",
    lastName: "Lee",
    email: undefined,
    number: undefined,
    sentDate: undefined,
    pledgedAmount: undefined,
    confirmedDate: undefined,
    confirmedAmount: undefined,
    notes: "",
    status: "To Ask",
  },
  {
    id: 6,
    firstName: "Olivia",
    lastName: "Clark",
    email: "olivia.clark@example.com",
    number: "+64210000007",
    sentDate: new Date("2023-08-20"),
    pledgedAmount: 1000,
    confirmedDate: new Date("2023-08-30"),
    confirmedAmount: 1000,
    notes: "Wants to discuss further opportunities.",
    status: "Confirmed",
  },
  {
    id: 7,
    firstName: "James",
    lastName: "Walker",
    email: "james.walker@example.com",
    number: "+64210000008",
    sentDate: undefined,
    pledgedAmount: undefined,
    confirmedDate: undefined,
    confirmedAmount: undefined,
    notes: "Will follow up next week.",
    status: "Letter Sent",
  },
  {
    id: 8,
    firstName: "Sophia",
    lastName: "Hall",
    email: "sophia.hall@example.com",
    number: "+64210000009",
    sentDate: new Date("2023-08-22"),
    pledgedAmount: undefined,
    confirmedDate: undefined,
    confirmedAmount: undefined,
    notes: "Waiting for response.",
    status: "Contacted",
  },
  {
    id: 9,
    firstName: "Liam",
    lastName: "Adams",
    email: "liam.adams@example.com",
    number: "+64210000010",
    sentDate: new Date("2023-08-23"),
    pledgedAmount: 750,
    confirmedDate: undefined,
    confirmedAmount: undefined,
    notes: "Tentatively agreed.",
    status: "Pledged",
  },
  {
    id: 10,
    firstName: "Ava",
    lastName: "Baker",
    email: "ava.baker@example.com",
    number: "+64210000011",
    sentDate: new Date("2023-08-24"),
    pledgedAmount: undefined,
    confirmedDate: undefined,
    confirmedAmount: undefined,
    notes: "Interested, but unsure.",
    status: "Contacted",
  },
  {
    id: 11,
    firstName: "William",
    lastName: "Evans",
    email: "william.evans@example.com",
    number: "+64210000012",
    sentDate: new Date("2023-08-25"),
    pledgedAmount: undefined,
    confirmedDate: undefined,
    confirmedAmount: undefined,
    notes: "Requires more details.",
    status: "Letter Sent",
  },
  {
    id: 12,
    firstName: "Mia",
    lastName: "Carter",
    email: "mia.carter@example.com",
    number: "+64210000013",
    sentDate: new Date("2023-08-26"),
    pledgedAmount: 600,
    confirmedDate: new Date("2023-09-01"),
    confirmedAmount: 600,
    notes: "Happy to contribute.",
    status: "Confirmed",
  },
  {
    id: 13,
    firstName: "Benjamin",
    lastName: "Phillips",
    email: undefined,
    number: undefined,
    sentDate: undefined,
    pledgedAmount: undefined,
    confirmedDate: undefined,
    confirmedAmount: undefined,
    notes: "",
    status: "To Ask",
  },
  {
    id: 14,
    firstName: "Charlotte",
    lastName: "Mitchell",
    email: "charlotte.mitchell@example.com",
    number: "+64210000015",
    sentDate: new Date("2023-08-27"),
    pledgedAmount: undefined,
    confirmedDate: undefined,
    confirmedAmount: undefined,
    notes: "Asked for more time to decide.",
    status: "Contacted",
  },
  {
    id: 15,
    firstName: "Elijah",
    lastName: "Perez",
    email: "elijah.perez@example.com",
    number: "+64210000016",
    sentDate: new Date("2023-08-28"),
    pledgedAmount: 800,
    confirmedDate: undefined,
    confirmedAmount: undefined,
    notes: "Needs confirmation.",
    status: "Pledged",
  },
  {
    id: 16,
    firstName: "Amelia",
    lastName: "Harris",
    email: "amelia.harris@example.com",
    number: "+64210000017",
    sentDate: new Date("2023-08-29"),
    pledgedAmount: 400,
    confirmedDate: new Date("2023-09-03"),
    confirmedAmount: 400,
    notes: "Looking forward to the partnership.",
    status: "Confirmed",
  },
  {
    id: 17,
    firstName: "Lucas",
    lastName: "Edwards",
    email: undefined,
    number: undefined,
    sentDate: undefined,
    pledgedAmount: undefined,
    confirmedDate: undefined,
    confirmedAmount: undefined,
    notes: "",
    status: "To Ask",
  },
  {
    id: 18,
    firstName: "Harper",
    lastName: "Collins",
    email: "harper.collins@example.com",
    number: "+64210000019",
    sentDate: new Date("2023-08-30"),
    pledgedAmount: undefined,
    confirmedDate: undefined,
    confirmedAmount: undefined,
    notes: "Possibly interested.",
    status: "Contacted",
  },
];
