import { ThemeProvider } from "@/components/ThemeProvider";
import type { Metadata } from "next";
import "./globals.css";
import { DataProvider } from "@/components/DataProvider";
import { PartnersProvider } from "@/components/PartnersProvider";
import { UsersProvider } from "@/components/UsersProvider/UsersProvider";

export const metadata: Metadata = {
  title: "Support Raising Tool",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DataProvider>
          <PartnersProvider>
            <UsersProvider>
              <ThemeProvider>{children}</ThemeProvider>
            </UsersProvider>
          </PartnersProvider>
        </DataProvider>
      </body>
    </html>
  );
}
